TEAM_MAP = {
    "LIGA PROFESIONAL DE FÚTBOL": [
        "Aldosivi",
        "Argentinos Jrs.",
        "Arsenal",
        "Atlético Tucumán",
        "Banfield",
        "Barracas Central",
        "Boca Juniors",
        "Central Córdoba",
        "Colón",
        "Defensa",
        "Estudiantes",
        "Gimnasia",
        "Godoy Cruz",
        "Huracán",
        "Independiente",
        "Lanús",
        "Newell's",
        "Patronato",
        "Platense",
        "Racing Club",
        "River Plate",
        "Rosario Central",
        "San Lorenzo",
        "Sarmiento",
        "Talleres",
        "Tigre",
        "Unión",
        "Vélez Sarsfield",
    ],
    "A-LEAGUE": [
        "Adelaide United",
        "Brisbane Roar",
        "Central Coast",
        "Macarthur FC",
        "Melb. Victory",
        "Melbourne City",
        "Newcastle Jets",
        "Perth Glory",
        "Sydney FC",
        "Well. Phoenix" "Western United" "WS Wanderers",
    ],
    "Ö. BUNDESLIGA": [
        "Austria Klagenfurt",
        "FK Austria Wien",
        "LASK",
        "RB Salzburg",
        "SC Austria",
        "SCR Altach",
        "SK Rapid Wien",
        "SK Sturm Graz",
        "SV Ried",
        "TSV Hartberg",
        "Wolfsberger AC",
        "WSG Tirol",
    ],
    "1A PRO LEAGUE": [
        "Cercle Brugge",
        "Club Brugge",
        "KAA Gent",
        "KAS Eupen",
        "KRC Genk",
        "KV Kortrijk",
        "KV Mechelen",
        "KV Oostende",
        "KVC Westerlo",
        "OH Leuven",
        "R. Union St.-G",
        "RFC Seraing",
        "Royal Antwerp FC",
        "RSC Anderlecht",
        "Sp. Charleroi",
        "Standard LiÃ¨ge",
        "STVV",
        "Zulte Waregem",
    ],
    "CSL": [
        "Beijing Guoan",
        "Cangzhou FC",
        "Changchun Yatai",
        "Dalian Pro",
        "Guangzhou City",
        "Guangzhou FC",
        "Hebei FC",
        "Henan SSLM FC",
        "Meizhou Hakka",
        "Rongcheng FC",
        "Shandong Taishan",
        "Shanghai Port",
        "Shanghai Shenhua",
        "Shenzhen FC",
        "Tianjin JMT FC",
        "Wuhan 3 Towns",
        "Wuhan FC",
        "Zhejiang Pro",
    ],
    "3F SUPERLIGA": [
        "AaB",
        "AC Horsens",
        "AGF",
        "BrÃ¸ndby IF",
        "F.C. KÃ¸benhavn",
        "FC Midtjylland",
        "FC NordsjÃ¦lland",
        "Lyngby BK",
        "Odense BK",
        "Randers FC",
        "Silkeborg IF",
        "Viborg FF",
    ],
    "PREMIER LEAGUE": [
        "AFC Bournemouth",
        "Arsenal",
        "Aston Villa",
        "Brentford",
        "Brighton",
        "Chelsea",
        "Crystal Palace",
        "Everton",
        "Fulham",
        "Leeds United",
        "Leicester City",
        "Liverpool",
        "Manchester City",
        "Manchester Utd",
        "Newcastle Utd",
        "Nott'm Forest",
        "Southampton",
        "Spurs",
        "West Ham",
        "Wolves",
    ],
    "EFL CHAMPIONSHIP": [
        "Birmingham City",
        "Blackburn Rovers",
        "Blackpool",
        "Bristol City",
        "Burnley",
        "Cardiff City",
        "Coventry City",
        "Huddersfield",
        "Hull City",
        "Luton Town",
        "Middlesbrough",
        "Millwall",
        "Norwich",
        "Preston",
        "QPR",
        "Reading",
        "Rotherham Utd",
        "Sheffield Utd",
        "Stoke City",
        "Sunderland",
        "Swansea City",
        "Watford",
        "West Brom",
        "Wigan Athletic",
    ],
    "EFL LEAGUE ONE": [
        "Accrington",
        "Barnsley",
        "Bolton",
        "Bristol Rovers",
        "Burton Albion",
        "Cambridge Utd",
        "Charlton Ath",
        "Cheltenham Town",
        "Derby County",
        "Exeter City",
        "Fleetwood Town",
        "Forest Green",
        "Ipswich",
        "Lincoln City",
        "MK Dons",
        "Morecambe",
        "Oxford United",
        "Peterborough",
        "Plymouth Argyle",
        "Port Vale",
        "Portsmouth",
        "Sheffield Wed",
        "Shrewsbury",
        "Wycombe",
    ],
    "EFL LEAGUE TWO": [
        "AFC Wimbledon",
        "Barrow",
        "Bradford City",
        "Carlisle United",
        "Colchester",
        "Crawley Town",
        "Crewe Alexandra",
        "Doncaster",
        "Gillingham",
        "Grimsby Town",
        "Harrogate Town",
        "Hartlepool",
        "Leyton Orient",
        "Mansfield Town",
        "Newport County",
        "Northampton",
        "Rochdale",
        "Salford City",
        "Stevenage",
        "Stockport",
        "Sutton United",
        "Swindon Town",
        "Tranmere Rovers",
        "Walsall",
    ],
    "LIGUE 1 UBER EATS": [
        "AC Ajaccio",
        "AJ Auxerre",
        "Angers SCO",
        "AS Monaco",
        "Clermont Foot 63",
        "ESTAC Troyes",
        "FC Lorient",
        "FC Nantes",
        "LOSC Lille",
        "Montpellier",
        "OGC Nice",
        "OL",
        "OM",
        "Paris SG",
        "RC Lens",
        "Stade Brestois 29",
        "Stade de Reims",
        "Stade Rennais FC",
        "Strasbourg",
        "Toulouse FC",
    ],
    "LIGUE 2 BKT": [
        "Amiens SC",
        "AS Saint-Ã‰tienne",
        "Bordeaux",
        "Dijon FCO",
        "En Avant Guingamp",
        "FC Annecy",
        "FC Metz",
        "FCSM",
        "Grenoble Foot 38",
        "Havre AC",
        "NÃ®mes Olympique",
        "Niort",
        "Paris FC",
        "Pau FC",
        "Quevilly Rouen",
        "Rodez AF",
        "SC Bastia",
        "SM Caen",
        "Stade Lavallois",
        "Valenciennes FC",
    ],
    "BUNDESLIGA": [
        "1. FC KÃ¶ln",
        "1. FSV Mainz 05",
        "Borussia Dortmund",
        "FC Augsburg",
        "FC Bayern MÃ¼nchen",
        "FC Schalke 04",
        "Frankfurt",
        "Hertha Berlin",
        "Leverkusen",
        "M'gladbach",
        "RB Leipzig",
        "SC Freiburg",
        "SV Werder Bremen",
        "TSG Hoffenheim",
        "Union Berlin",
        "VfB Stuttgart",
        "VfL Bochum",
        "VfL Wolfsburg",
    ],
    "BUNDESLIGA 2": [
        "1. FC Magdeburg",
        "1. FC NÃ¼rnberg",
        "Arminia Bielefeld",
        "Braunschweig",
        "DÃ¼sseldorf",
        "FC St. Pauli",
        "FÃ¼rth",
        "Hamburger SV",
        "Hannover 96",
        "Hansa Rostock",
        "Heidenheim",
        "Holstein Kiel",
        "Jahn Regensburg",
        "Kaiserslautern",
        "Karlsruher SC",
        "SC Paderborn 07",
        "SV Darmstadt 98",
        "SV Sandhausen",
    ],
    "3. LIGA": [
        "1860 MÃ¼nchen",
        "B. Dortmund II",
        "Dynamo Dresden",
        "FC Erzgebirge Aue",
        "FC Ingolstadt 04",
        "FSV Zwickau",
        "Hallescher FC",
        "MSV Duisburg",
        "Rot-Weiss Essen",
        "SaarbrÃ¼cken",
        "SC Freiburg II",
        "SC Verl",
        "SpVgg Bayreuth",
        "SV Elversberg",
        "SV Meppen",
        "SV Waldhof",
        "VfB Oldenburg",
        "VfL OsnabrÃ¼ck",
        "Viktoria KÃ¶ln",
        "Wehen Wiesbaden",
    ],
    "Hero ISL": [
        "ATK Mohun Bagan",
        "Bengaluru FC",
        "Chennaiyin FC",
        "East Bengal",
        "FC Goa",
        "Hyderabad FC",
        "Jamshedpur FC",
        "Kerala Blasters",
        "Mumbai City FC",
        "NorthEast United",
        "Odisha FC",
    ],
    "SERIE A TIM": [
        "Bergamo Calcio**",
        "Bologna",
        "Cremonese",
        "Empoli",
        "Fiorentina",
        "Hellas Verona",
        "Inter",
        "Juventus",
        "Latium**",
        "Lecce",
        "Milan",
        "Monza",
        "Napoli FC**",
        "Roma FC**",
        "Salernitana",
        "Sampdoria",
        "Sassuolo",
        "Spezia",
        "Torino",
        "Udinese",
    ],
    "MEIJI YASUDA J1": [
        "Ascoli",
        "Bari",
        "Benevento",
        "Brescia",
        "Cagliari",
        "Cittadella",
        "Como",
        "Cosenza",
        "Frosinone",
        "Genoa",
        "Modena",
        "Palermo",
        "Parma",
        "Perugia",
        "Pisa",
        "Reggina",
        "SPAL",
        "SÃ¼dtirol",
        "Ternana",
        "Venezia",
    ],
    "K LEAGUE 1": [
        "Daegu FC",
        "FC Seoul",
        "Gangwon FC",
        "Gimcheon Sangmu",
        "Incheon United",
        "Jeju United",
        "Jeonbuk Hyundai",
        "Pohang Steelers",
        "Seongnam FC",
        "Suwon FC",
        "Suwon Samsung",
        "Ulsan Hyundai",
    ],
    "International": [
        "Argentina",
        "Australia",
        "Austria",
        "Belgium",
        "Brazil (Authentic kits and badges, generic players)",
        "Canada",
        "China PR",
        "Croatia",
        "Czech Republic",
        "Denmark",
        "England",
        "Finland",
        "France",
        "Germany",
        "Ghana",
        "Hungary",
        "Iceland",
        "Ireland",
        "Italy",
        "Mexico",
        "Morocco",
        "Netherlands",
        "New Zealand",
        "Northern Ireland",
        "Norway",
        "Poland",
        "Portugal",
        "Qatar",
        "Romania",
        "Scotland",
        "Spain",
        "Sweden",
        "Ukraine",
        "United States",
        "Wales",
    ],
    "EREDIVISIE": [
        "Ajax",
        "AZ",
        "Excelsior",
        "FC Emmen",
        "FC Groningen",
        "FC Twente",
        "FC Utrecht",
        "FC Volendam",
        "Feyenoord",
        "Fortuna Sittard",
        "Go Ahead Eagles",
        "N.E.C. Nijmegen",
        "PSV",
        "RKC Waalwijk",
        "SC Cambuur",
        "sc Heerenveen",
        "Sparta Rotterdam",
        "Vitesse",
    ],
    "ELITESERIEN": [
        "Aalesunds FK",
        "FK BodÃ¸/Glimt",
        "FK Haugesund",
        "FK Jerv",
        "HamKam Fotball",
        "Kristiansund BK",
        "LillestrÃ¸m SK",
        "Molde FK",
        "Odds BK",
        "Rosenborg BK",
        "Sandefjord",
        "Sarpsborg 08",
        "StrÃ¸msgodset IF",
        "TromsÃ¸ IL",
        "VÃ¥lerenga Fotball",
        "Viking FK",
    ],
    "POLISH - PKO EKSTRAKLASA": [
        "Cracovia",
        "Górnik Zabrze",
        "Jagiellonia",
        "Korona Kielce",
        "Lech Poznań",
        "Lechia Gdańsk",
        "Legia Warszawa",
        "Miedź Legnica",
        "Piast Gliwice",
        "Pogoń Szczecin",
        "Radomiak Radom",
        "Raków",
        "Śląsk Wrocław",
        "Stal Mielec",
        "Warta Poznań",
        "Widzew Łódź",
        "Wisła Płock",
        "Zagłębie Lubin",
    ],
    "LIGA PORTUGAL": [
        "Arouca",
        "Boavista FC",
        "Casa Pia AC",
        "Estoril Praia",
        "FC FamalicÃ£o",
        "FC Porto",
        "FC Vizela",
        "GD Chaves",
        "Gil Vicente",
        "MarÃ\xadtimo",
        "PaÃ§os Ferreira",
        "Portimonense SC",
        "Rio Ave FC",
        "Santa Clara",
        "SC Braga",
        "SL Benfica",
        "Sporting CP",
        "VitÃ³ria SC",
    ],
    "SSE AIRTRICITY PREMIER DIVISION": [
        "Bohemian FC",
        "Derry City",
        "Drogheda United",
        "Dundalk",
        "Finn Harps",
        "Shamrock Rovers",
        "Shelbourne",
        "Sligo Rovers",
        "St. Pats",
        "UCD AFC",
    ],
    "Rest of World": [
        "adidas All-Star",
        "AEK Athens",
        "Al Ain FC",
        "Apoel FC",
        "Atl. Nacional",
        "Dinamo Zagreb",
        "Dynamo Kyiv",
        "FerencvÃ¡rosi TC",
        "Hajduk Split",
        "HJK Helsinki",
        "Kaizer Chiefs",
        "Mamelodi Sundowns",
        "MLS All Stars",
        "Orlando Pirates",
        "Panathinaikos",
        "PAOK FC",
        "Shakhtar Donetsk",
        "Slavia Praha",
        "Soccer Aid",
        "Sparta Praha",
        "Viktoria PlzeÅˆ",
        "Wrexham AFC",
    ],
    "Romanian SUPERLIGA": [
        "AFC Chindia",
        "CFR 1907 Cluj",
        "CS Mioveni",
        "Farul ConstanÈ›a",
        "FC ArgeÈ™",
        "FC BotoÈ™ani",
        "FC Hermannstadt",
        "FC Petrolul",
        "FC Rapid 1923",
        "FC Univ. Cluj",
        "FC Voluntari",
        "FCSB",
        "FCU 1948",
        "Sepsi OSK",
        "Univ. Craiova",
        "UTA Arad",
    ],
    "MBS PRO LEAGUE": [
        "Abha Club",
        "Al Adalah",
        "Al Batin",
        "Al Fateh",
        "Al Fayha",
        "Al Hilal",
        "Al Ittihad",
        "Al Khaleej",
        "Al Nassr",
        "Al Raed",
        "Al Shabab",
        "Al Taawoun",
        "Al Tai",
        "Al Wehda",
        "Damac FC",
        "Ettifaq FC",
    ],
    "CINCH PREMIERSHIP": [
        "Aberdeen",
        "Celtic",
        "Dundee United",
        "Hearts",
        "Hibernian",
        "Kilmarnock",
        "Livingston",
        "Motherwell",
        "Rangers",
        "Ross County",
        "St. Johnstone",
        "St. Mirren",
    ],
    "LALIGA SANTANDER": [
        "Athletic Club",
        "AtlÃ©tico de Madrid",
        "CA Osasuna",
        "CÃ¡diz CF",
        "Elche CF",
        "FC Barcelona",
        "Getafe CF",
        "Girona FC",
        "R. Valladolid CF",
        "Rayo Vallecano",
        "RC Celta",
        "RCD Espanyol",
        "RCD Mallorca",
        "Real Betis",
        "Real Madrid",
        "Real Sociedad",
        "Sevilla FC",
        "UD AlmerÃ\xada",
        "Valencia CF",
        "Villarreal CF",
    ],
    "LALIGA SMARTBANK": [
        "Albacete BP",
        "Burgos CF",
        "CD LeganÃ©s",
        "CD Lugo",
        "CD MirandÃ©s",
        "CD Tenerife",
        "D. AlavÃ©s",
        "FC Andorra",
        "FC Cartagena",
        "Granada CF",
        "Levante UD",
        "MÃ¡laga CF",
        "R. Oviedo",
        "R. Racing Club",
        "R. Sporting",
        "Real Zaragoza",
        "SD Eibar",
        "SD Huesca",
        "SD Ponferradina",
        "UD Ibiza",
        "UD Las Palmas",
        "Villarreal CF B",
    ],
    "SWEDISH - ALLSVENSKAN": [
        "AIK",
        "BK HÃ¤cken",
        "Degerfors IF",
        "DjurgÃ¥rdens IF",
        "GIF Sundsvall",
        "Hammarby IF",
        "Helsingborgs IF",
        "IF Elfsborg",
        "IFK GÃ¶teborg",
        "IFK NorrkÃ¶ping",
        "IFK VÃ¤rnamo",
        "IK Sirius",
        "Kalmar FF",
        "MalmÃ¶ FF",
        "MjÃ¤llby AIF",
        "Varbergs BoIS",
    ],
    "CREDIT SUISSE SUPER LEAGUE": [
        "BSC Young Boys",
        "FC Basel 1893",
        "FC Lugano",
        "FC Luzern",
        "FC Sion",
        "FC St. Gallen",
        "FC Winterthur",
        "FC ZÃ¼rich",
        "Grasshopper Club",
        "Servette FC",
    ],
    "SÜPER LİG": [
        "Adana Demirspor",
        "Alanyaspor",
        "Antalyaspor",
        "BaÅŸakÅŸehir",
        "BeÅŸiktaÅŸ",
        "FenerbahÃ§e",
        "Galatasaray",
        "Gaziantep",
        "Giresunspor",
        "Hatayspor",
        "Ä°stanbulspor",
        "KaragÃ¼mrÃ¼k SK",
        "KasÄ±mpaÅŸa",
        "Kayserispor",
        "Konyaspor",
        "MKE AnkaragÃ¼cÃ¼",
        "Sivasspor",
        "Trabzonspor",
        "Ãœmraniyespor",
    ],
    "MLS": [
        "Atlanta United",
        "Austin FC",
        "CF MontrÃ©al",
        "Charlotte FC",
        "Chicago Fire FC",
        "Colorado Rapids",
        "Columbus Crew",
        "D.C. United",
        "FC Cincinnati",
        "FC Dallas",
        "Houston Dynamo",
        "Inter Miami CF",
        "LA Galaxy",
        "LAFC",
        "Minnesota United",
        "Nashville SC",
        "New England",
        "New York City FC",
        "Orlando City",
        "Philadelphia",
        "Portland Timbers",
        "Real Salt Lake",
        "Red Bulls",
        "SJ Earthquakes",
        "Sounders FC",
        "Sporting KC",
        "Toronto FC",
        "Whitecaps FC",
    ],
}
